import Head from 'next/head'
import Card from '../components/card';
import styles from '../styles/Home.module.css'
import Footer from '../components/footer';

export async function getStaticProps(context) {

  const noticias = await fetch('http://localhost:1337/noticias')
    .then(res => res.json());

  return {
    props: { noticias: noticias || [] }, // will be passed to the page component as props
  }
}


export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {props.noticias.map(noticia => <Card
          titulo={noticia.Titulo}
          texto={noticia.Corpo}
          image={`http://localhost:1337${noticia.Imagem.url}`}
        />)}
      </main>
      <Footer></Footer>
    </div>
  )
}
